name: Publish package
on:
  workflow_dispatch:
    inputs:
      increment:
        description: 'Release increment (e.g. patch, minor, major)'
        required: true
        type: choice
        options:
          - patch
          - minor
          - major
concurrency:
  group: ${{ github.workflow }}
run-name: 'Release ${{ github.event.inputs.increment }} version'
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout commit
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 23
          cache: npm
      - name: Setup git config
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
      - name: Setup npm config
        run: |
          npm config set //registry.npmjs.org/:_authToken $NPM_TOKEN
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Install dependencies
        run: npm ci
      - name: Release package
        run: |
          ARGS=""
          if [[ "${{ github.event.inputs.increment }}" != "none" ]]; then
            ARGS+="${{ github.event.inputs.increment }}"
          fi
          npm run release -- $ARGS --ci
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
